[package]
name = "newrelic_plugin"
version = "0.1.0"
authors = ["msamir"]

[dependencies]
chrono = "0.4"
log = "0.4"
num = "0.2"
num-traits = "0.2"
serde_json = "1.0"
curl = "0.4.18"
log4rs = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
